from typing import TypedDict, Annotated, Any
from langgraph.graph.message import add_messages
from langchain_core.messages import AnyMessage
from pydantic import BaseModel, Field

class PlanStep(BaseModel):
    """Pydantic model representing a single step in a task plan."""
    step_id: int = Field(description="The sequential order or ID of the step")
    task_description: str = Field(description="Detailed description of what needs to be done")
    assignee: str = Field(description="The agent assigned to this task (e.g., Researcher, Executor, Critic)")

class Plan(BaseModel):
    """Pydantic model representing the overall plan composed of multiple steps."""
    steps: list[PlanStep] = Field(description="List of steps required to accomplish the task")

class AgentState(TypedDict):
    """
    Main state schema for the LangGraph multi-agent system.
    """
    # Using the built-in add_messages reducer from LangGraph to append messages properly
    messages: Annotated[list[AnyMessage], add_messages]
    
    # Original user task
    task: str
    
    # The detailed plan generated by the Planner agent
    plan: list[dict[str, Any]]
    
    # Context or retrieved data from the Researcher agent
    research_results: list[dict[str, Any]]
    
    # Current draft from the Executor/Writer agent
    draft: str
    
    # Feedback from the Critic agent
    critique: str
    
    # Score evaluating the draft quality
    critique_score: float
    
    # Final generated output
    final_output: str
    
    # Track the number of iterations or routing steps
    iteration: int
    
    # Next node/agent to route to
    next: str
